version: '3.6'

services:

  postfix:
    image: vladchernikov/postfix
    volumes:
      - ./main.cf:/etc/postfix/main.cf
      - ./smtpd.conf:/etc/sasl2/smtpd.conf
      - ./sasldb2:/etc/sasldb2
    ports:
      - "25:25"
